# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lmtools',
                'doc_host': 'https://jph00.github.io',
                'git_url': 'https://github.com/jph00/lmtools',
                'lib_path': 'lmtools'},
  'syms': {'lmtools.core': {'lmtools.core.foo': ('core.html#foo', 'lmtools/core.py')}}}
