# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_funccall.ipynb.

# %% auto #0
__all__ = ['empty', 'custom_types', 'type_map', 'get_schema', 'python', 'mk_ns', 'resolve_nm', 'get_schema_nm', 'call_func',
           'call_func_async', 'mk_param', 'schema2sig', 'mk_tool']

# %% ../01_funccall.ipynb #e5ad6b86
import inspect, ast, keyword
from collections import abc
from fastcore.utils import *
from fastcore.docments import docments
from typing import get_origin, get_args, Optional, Union, Any
from types import UnionType
from typing import get_type_hints
from inspect import Parameter, Signature
from decimal import Decimal
from uuid import UUID
from functools import reduce

# %% ../01_funccall.ipynb #a9f43047
empty = inspect.Parameter.empty

# %% ../01_funccall.ipynb #4d5dc245
def _param(info, evalable=False):
    "JSON schema non-type metadata for a parameter"
    pschema = dict(description=info.docment or "")
    if info.default is not empty:
        if evalable:
            try: ast.literal_eval(repr(info.default))
            except: pschema["default"] = str(info.default)
            else: pschema["default"] = info.default
        else: pschema["default"] = info.default
    return pschema

# %% ../01_funccall.ipynb #f77bea1c
custom_types = {Path, bytes, Decimal, UUID}
_tmap = {int: "integer", float: "number", str: "string", bool: "boolean", list: "array", dict: "object"}
_nmap = {k.__name__: v for k, v in _tmap.items()}

def _type_str(t):
    "JSON Schema type name for a type or string annotation"
    if isinstance(t, str): return _nmap.get(t, "object")
    base = _tmap.get(get_origin(t) or t, _nmap.get(getattr(t, '__name__', ''), "object"))
    if (args := get_args(t)): return f"{base}[{', '.join(_type_str(a) for a in args if a is not Ellipsis)}]"
    return base

# %% ../01_funccall.ipynb #c141588b
def _handle_type(t, defs):
    "Convert a type annotation to JSON Schema"
    ot = ifnone(get_origin(t), t)
    if t is NoneType: return {'type': 'null'}
    if ot in (Union, UnionType): return {"anyOf": [_handle_type(arg, defs) for arg in get_args(t)]}
    if t in custom_types: return {'type': 'string', 'format': t.__name__}
    if ot is dict:
        args = get_args(t)
        return {'type': 'object', 'additionalProperties': _handle_type(args[1], defs)} if args else {'type': 'object'}
    if ot is tuple:
        args = get_args(t)
        if not args: return {'type': 'array', 'items': {}}
        if args[-1] is Ellipsis: return {'type': 'array', 'items': _handle_type(args[0], defs)}
        prefix = [_handle_type(a, defs) for a in args]
        items = prefix[0] if all(p == prefix[0] for p in prefix) else {'anyOf': prefix}
        return {'type': 'array', 'prefixItems': prefix, 'items': items, 'minItems': len(args), 'maxItems': len(args)}
    if ot in (list, set):
        args = get_args(t)
        schema = {'type': 'array', 'items': _handle_type(args[0], defs) if args else {}}
        if ot is set: schema['uniqueItems'] = True
        return schema
    if isinstance(t, type) and not issubclass(t, (int, float, str, bool)) and t.__module__ != 'builtins' or inspect.isfunction(t):
        defs[t.__name__] = _get_nested_schema(t)
        return {'$ref': f'#/$defs/{t.__name__}'}
    return {'type': _type_str(t)}

# %% ../01_funccall.ipynb #e0840bf5
def _process_property(name, obj, props, req, defs, evalable=False):
    "Process a single property of the schema"
    p = _param(obj, evalable=evalable)
    props[name] = p
    if obj.default is empty: req[name] = True
    p.update(_handle_type(obj.anno, defs))
    if 'anyOf' in p: p.pop('type', None)

# %% ../01_funccall.ipynb #38b0f97e
def _get_nested_schema(obj, evalable=False, skip_hidden=False):
    "Generate nested JSON schema for a class or function"
    d = docments(obj, full=True)
    props, req, defs = {}, {}, {}

    for n, o in d.items():
        if n != 'return' and n != 'self' and not (skip_hidden and n.startswith('_')):
            _process_property(n, o, props, req, defs, evalable=evalable)

    tkw = {}
    if isinstance(obj, type): tkw['title']=obj.__name__
    schema = dict(type='object', properties=props, **tkw)
    if req: schema['required'] = list(req)
    if defs: schema['$defs'] = defs
    return schema


# %% ../01_funccall.ipynb #748da965
def get_schema(
    f:Union[callable,dict], # Function to get schema for
    pname='input_schema',   # Key name for parameters
    evalable=False,  # stringify defaults that can't be literal_eval'd?
    skip_hidden=False, # skip parameters starting with '_'?
    name=None # Override function name (useful for dotted paths like 'obj.method')
)->dict: # {'name':..., 'description':..., pname:...}
    "Generate JSON schema for a class, function, or method"
    if isinstance(f, dict): return f
    if hasattr(f, '__call__') and not isinstance(f, type) and not inspect.isfunction(f) and not inspect.ismethod(f):
        orig_doc = f.__doc__
        f = f.__call__
    else: orig_doc = None
    schema = _get_nested_schema(f, evalable=evalable, skip_hidden=skip_hidden)
    desc = f.__doc__ or orig_doc
    assert desc, "Docstring missing!"
    d = docments(f, full=True)
    ret = d.pop('return')
    has_type = (ret.anno is not empty) and (ret.anno is not None)
    has_doc = ret.docment
    if has_type or has_doc:
        type_str = f'type: {_type_str(ret.anno)}' if has_type else None
        ret_str = f'{ret.docment} ({type_str})' if has_type and has_doc else (type_str if has_type else ret.docment)
        desc += f'\n\nReturns:\n- {ret_str}'
    return {"name": name or f.__name__, "description": desc, pname: schema}

# %% ../01_funccall.ipynb #873000d7
import ast, signal, traceback
from fastcore.utils import *

# %% ../01_funccall.ipynb #4703296a
def _copy_loc(new, orig):
    "Copy location information from original node to new node and all children."
    new = ast.copy_location(new, orig)
    for field, o in ast.iter_fields(new):
        if isinstance(o, ast.AST): setattr(new, field, _copy_loc(o, orig))
        elif isinstance(o, list): setattr(new, field, [_copy_loc(value, orig) for value in o])
    return new

# %% ../01_funccall.ipynb #1574585f
def _run(code:str, glb:dict=None, loc:dict=None):
    "Run `code`, returning final expression (similar to IPython)"
    tree = ast.parse(code)
    last_node = tree.body[-1] if tree.body else None
    
    # If the last node is an expression, modify the AST to capture the result
    if isinstance(last_node, ast.Expr):
        tgt = [ast.Name(id='_result', ctx=ast.Store())]
        assign_node = ast.Assign(targets=tgt, value=last_node.value)
        tree.body[-1] = _copy_loc(assign_node, last_node)

    compiled_code = compile(tree, filename='<ast>', mode='exec')
    glb = glb or {}
    stdout_buffer = io.StringIO()
    saved_stdout = sys.stdout
    sys.stdout = stdout_buffer
    try: exec(compiled_code, glb, loc)
    finally: sys.stdout = saved_stdout
    _result = glb.get('_result', None)
    if _result is not None: return _result
    return stdout_buffer.getvalue().strip()

# %% ../01_funccall.ipynb #81857615
def python(
    code:str, # Code to execute
    glb:Optional[dict]=None, # Globals namespace
    loc:Optional[dict]=None, # Locals namespace
    timeout:int=3600 # Maximum run time in seconds
):
    "Executes python `code` with `timeout` and returning final expression (similar to IPython)."
    def handler(*args): raise TimeoutError()
    if glb is None: glb = inspect.currentframe().f_back.f_globals
    if loc is None: loc=glb
    signal.signal(signal.SIGALRM, handler)
    signal.alarm(timeout)
    try: return _run(code, glb, loc)
    except Exception as e: return traceback.format_exc()
    finally: signal.alarm(0)

# %% ../01_funccall.ipynb #782c4415
def mk_ns(fs):
    if isinstance(fs, abc.Mapping): return fs
    merged = {}
    for o in listify(fs):
        if isinstance(o, dict): merged |= o
        elif callable(o) and hasattr(o, '__name__'): merged |= {o.__name__: o}
    return merged

# %% ../01_funccall.ipynb #6ef23838
def _coerce_inputs(func, inputs):
    "Coerce inputs based on function type annotations"
    hints = get_type_hints(func) if hasattr(func, '__annotations__') else {}
    res = {}
    for k,v in inputs.items():
        ann = hints.get(k)
        if ann in custom_types: res[k] = ann(v)
        elif isinstance(v, dict) and callable(ann): res[k] = ann(**v)
        else: res[k] = v
    return res

# %% ../01_funccall.ipynb #925f462b
def resolve_nm(nm, ns):
    st,*rest = nm.split('.')
    return reduce(getattr, rest, ns[st])

# %% ../01_funccall.ipynb #6f6b5bfa
def get_schema_nm(nm:str, ns, dot2dash=False, **kwargs):
    "Get schema for symbol `nm` in namespace `ns`, preserving the full dotted name"
    name = nm.replace('.', '-') if dot2dash else nm
    return get_schema(resolve_nm(nm, ns), name=name, **kwargs)

# %% ../01_funccall.ipynb #f1e7f8b4
def _norm_nm(nm, repl=''): return re.sub(r'\W', repl, nm)

# %% ../01_funccall.ipynb #2fca0f67
def _py_nm(nm):
    nm = _norm_nm(nm, '_')
    if not nm: return '_'
    if nm and nm[0].isdigit(): nm = f'_{nm}'
    if keyword.iskeyword(nm): nm = f'{nm}_'
    return nm

# %% ../01_funccall.ipynb #1625929e
def _nm_map(nms):
    py2orig = {}
    for orig in nms:
        pynm = _py_nm(orig)
        prev = py2orig.get(pynm)
        if prev is not None and prev != orig:
            raise ValueError(f'Name collision after sanitizing: {prev!r} and {orig!r} -> {pynm!r}')
        py2orig[pynm] = orig
    return py2orig

# %% ../01_funccall.ipynb #47b49644
def call_func(fc_name, fc_inputs, ns, raise_on_err=True):
    "Call the function `fc_name` with the given `fc_inputs` using namespace `ns`."
    if not isinstance(ns, abc.Mapping): ns = mk_ns(ns)
    func = resolve_nm(fc_name, ns)
    inps = {_norm_nm(k):v for k,v in fc_inputs.items()}
    inps = _coerce_inputs(func, inps)
    try: return func(**inps)
    except Exception as e:
        if raise_on_err: raise e from None
        else: return traceback.format_exc()

# %% ../01_funccall.ipynb #73bca085
async def call_func_async(fc_name, fc_inputs, ns, raise_on_err=True):
    "Awaits the function `fc_name` with the given `fc_inputs` using namespace `ns`."
    if not isinstance(ns, abc.Mapping): ns = mk_ns(ns)
    func = resolve_nm(fc_name, ns)
    try:
        res = call_func(fc_name, fc_inputs, ns, raise_on_err=raise_on_err)
        res = await maybe_await(res)
    except Exception as e:
        if raise_on_err: raise e from None
        else: return traceback.format_exc()
    return res

# %% ../01_funccall.ipynb #5a2588d5
type_map = dict(string=str, boolean=bool, integer=int, number=float, array=list, object=dict)

def mk_param(orig, props, req, pynm=None):
    "Create a `Parameter` for `orig` with schema `props`"
    pynm = ifnone(pynm, orig)
    kind = Parameter.POSITIONAL_OR_KEYWORD if orig in req else Parameter.KEYWORD_ONLY
    default = Parameter.empty if orig in req else props.get('default')
    if props.get('type') == 'array' and 'items' in props:
        item_type = type_map.get(props['items'].get('type'), Any)
        anno = list[item_type]
    else: anno = type_map.get(props.get('type'), Any)
    return Parameter(pynm, kind, default=default, annotation=anno)

# %% ../01_funccall.ipynb #a8befff6
def schema2sig(tool):
    "Convert json schema `tool` to a `Signature`"
    props, req = tool.inputSchema['properties'], tool.inputSchema.get('required', [])
    py2orig = _nm_map(props)
    params = sorted([mk_param(orig, props[orig], req, pynm) for pynm, orig in py2orig.items()], key=lambda p: p.kind)
    return Signature(params)

# %% ../01_funccall.ipynb #bb16561a
def mk_tool(dispfn, tool):
    "Create a callable function from a JSON schema tool definition"
    sig = schema2sig(tool)
    py2orig = _nm_map(tool.inputSchema['properties'])
    def fn(*args, **kwargs):
        bound = sig.bind(*args, **kwargs)
        kwargs = {py2orig.get(k, k):v for k,v in bound.arguments.items()}
        return dispfn(tool.name, **kwargs)
    fn.__doc__ = tool.description
    fn.__signature__ = sig
    fn.__name__ = fn.__qualname__ = tool.name
    fn.__annotations__ = {k: p.annotation for k, p in sig.parameters.items()}
    return fn
