"""Parse Markdown into heading-addressable sections while preserving each section's source text

Docs: https://AnswerDotAI.github.io/toolslm/md_hier.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_md_hier.ipynb.

# %% auto #0
__all__ = ['HeadingDict', 'create_heading_dict', 'create_heading_dict_file']

# %% ../nbs/04_md_hier.ipynb #9a8d208a
import re
from fastcore.tools import lnhash
from fastcore.utils import *

# %% ../nbs/04_md_hier.ipynb #0ac961ea
class HeadingDict(dict):
    "A dictionary of child headings with the section Markdown in `text`."
    def __init__(self, text='', start_line=1, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.text,self.start_line = text,start_line

    def paths(self):
        "List every heading path as a tuple."
        res = []
        for title,node in self.items():
            res.append((title,))
            res += [(title,*path) for path in node.paths()]
        return res

    def at(self, *path):
        "Return the node at `path`."
        node = self
        for title in path: node = node[title]
        return node

    def find(self, title):
        "Return the node whose heading is uniquely named `title`."
        paths = [path for path in self.paths() if path[-1] == title]
        if len(paths) != 1: raise KeyError(f"Expected one heading named {title!r}, found {len(paths)}: {paths}")
        return self.at(*paths[0])

    def refresh(self):
        "Fresh tree re-read from `path` (roots from `create_heading_dict_file` only)"
        return create_heading_dict_file(self.path)

    def view(self,
        nums=False, # Prefix lines with document-absolute line numbers, `lineno: `
        lnhashs=False # Prefix `lineno|hash|` exhash addresses instead; wins over `nums`
    ):
        "Section source with document-absolute line prefixes, so an editor can address the source file directly"
        lines = self.text.splitlines()
        if lnhashs: return PrettyString('\n'.join(lnhash(self.start_line+i, l)+l for i,l in enumerate(lines)))
        if nums: return PrettyString('\n'.join(f'{self.start_line+i}: {l}' for i,l in enumerate(lines)))
        return self.text

# %% ../nbs/04_md_hier.ipynb #db2212b5
def create_heading_dict(text, rm_fenced=True):
    "Create a nested `HeadingDict` from Markdown headings."
    lines = text.splitlines()
    headings,fence = [],None
    for i,line in enumerate(lines):
        if match := re.match(r'^\s*(`{3,}|~{3,})', line):
            marker = match[1][0]
            if fence == marker: fence = None
            elif fence is None: fence = marker
            if rm_fenced: continue
        if fence and rm_fenced: continue
        if match := re.match(r'^(#{1,6})\s+(.+?)\s*#*\s*$', line):
            headings.append(dict(level=len(match[1]), title=match[2], line=i))

    for i,heading in enumerate(headings):
        end = next((h['line'] for h in headings[i+1:] if h['level'] <= heading['level']), len(lines))
        heading['text'] = '\n'.join(lines[heading['line']:end]).strip()

    result = HeadingDict(text)
    stack,levels = [result],[0]
    for heading in headings:
        while len(stack) > 1 and levels[-1] >= heading['level']:
            stack.pop()
            levels.pop()
        parent,title = stack[-1],heading['title']
        if title in parent: raise ValueError(f"Duplicate sibling heading {title!r}")
        parent[title] = node = HeadingDict(heading['text'], heading['line']+1)
        stack.append(node)
        levels.append(heading['level'])
    return result

# %% ../nbs/04_md_hier.ipynb #f79f8f5b
def create_heading_dict_file(path, rm_fenced=True):
    "Create a `HeadingDict` from the Markdown file at `path` (`~` ok), recording `path` for `refresh`"
    path = Path(path).expanduser()
    res = create_heading_dict(path.read_text(), rm_fenced)
    res.path = path
    return res
