"""Parse Markdown into heading-addressable sections while preserving each section's source text

Docs: https://AnswerDotAI.github.io/toolslm/md_hier.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_md_hier.ipynb.

# %% auto #0
__all__ = ['Link', 'Sections', 'HeadingDict', 'create_heading_dict', 'create_heading_dict_file', 'Links']

# %% ../nbs/04_md_hier.ipynb #9a8d208a
import re, httpx
from urllib.parse import urljoin
from fastcore.tools import lnhash
from fastcore.utils import *

# %% ../nbs/04_md_hier.ipynb #3575b8f2
_LINK_RE = re.compile(r'(?<!\!)\[([^\]]*)\]\(([^)\s]+)\)')

class Link:
    "One inline link, numbered in document reading order"
    def __init__(self,
        n,    # 1-based number, in document reading order
        txt,  # The link text
        url,  # The link target (never shown by `__repr__`; the number stands for it)
        tail, # The rest of the link's line, as context - an llms.txt entry's description
        line, # Document-absolute 1-based line number
    ): store_attr()
    def __repr__(self): return f'[{self.n}] {self.txt}' + (f': {self.tail}' if self.tail else '')

class Sections(L):
    "Sections listed as `addr title` rows; each row is the live node"
    def __init__(self, items=None, counts=None, **kw):
        super().__init__(items, **kw)
        self.counts = counts
    def __getitem__(self, idx):
        res = super().__getitem__(idx)
        return Sections(res) if isinstance(idx, slice) else res
    def __repr__(self):
        if self.counts: return '\n'.join(f'{n.addr or "."} {n.title} ({c})' for n,c in zip(self, self.counts))
        return '\n'.join(f'{n.addr or "."} {n.title}' for n in self)

# %% ../nbs/04_md_hier.ipynb #0ac961ea
class HeadingDict(dict):
    "A dictionary of numbered child sections, with the section Markdown in `text`."
    title,addr = '',''
    def __init__(self, src='', start_line=1, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.src,self.start_line = src,start_line

    @property
    def end_line(self):
        "Document-absolute 1-based line number of this section's last line."
        return self.start_line + len(self.src.splitlines()) - 1

    @property
    def text(self):
        "Section Markdown, with each parsed inline link rendered as `[text][n]`."
        links = getattr(getattr(self, 'root', None), '_links', None)
        if not links: return self.src
        res = []
        for i,line in enumerate(self.src.splitlines()):
            here = [l for l in links if l.line == self.start_line+i]
            if here:
                it = iter(here)
                line = _LINK_RE.sub(lambda m: f'[{m[1]}][{next(it).n}]', line)
            res.append(line)
        return '\n'.join(res)

    def _walk(self):
        for node in self.values():
            yield node
            yield from node._walk()

    def paths(self,
        depth=None, # Deepest address depth to include; None for all
    ):
        "Outline of every section as `addr title` rows; each row is the live node"
        ns = self._walk()
        if depth: ns = (n for n in ns if n.addr.count('.') < depth)
        return Sections(ns)

    def at(self, *path):
        "The node at `path`: a dotted address like `'1.4.5'` (resolved from the root), or key ints (resolved from here)"
        if len(path) == 1 and isinstance(path[0], str):
            node = self.root
            for k in path[0].split('.'): node = node[int(k)]
            return node
        node = self
        for k in path: node = node[k]
        return node

    def find(self, title):
        "The unique section titled `title`; raises if absent or ambiguous"
        ms = [n for n in self._walk() if n.title == title]
        if len(ms) != 1: raise KeyError(f"Expected one heading named {title!r}, found {len(ms)}: {[n.addr for n in ms]}")
        return ms[0]

    def refresh(self):
        "Fresh tree re-read from `path` (roots from `create_heading_dict_file` only)"
        return create_heading_dict_file(self.path)

    def view(self,
        nums=False, # Prefix lines with document-absolute line numbers, `lineno: `
        lnhashs=False # Prefix `lineno|hash|` exhash addresses instead; wins over `nums`
    ):
        "Source exactly as stored, links unnumbered, so an editor can address the source file directly"
        lines = self.src.splitlines()
        if lnhashs: return PrettyString('\n'.join(lnhash(self.start_line+i, l)+l for i,l in enumerate(lines)))
        if nums: return PrettyString('\n'.join(f'{self.start_line+i}: {l}' for i,l in enumerate(lines)))
        return self.src

# %% ../nbs/04_md_hier.ipynb #db2212b5
def create_heading_dict(text, rm_fenced=True, base=None):
    "Create a nested `HeadingDict` from Markdown headings, numbering sections and inline links in reading order."
    lines = text.splitlines()
    headings,links,fence = [],[],None
    for i,line in enumerate(lines):
        if match := re.match(r'^\s*(`{3,}|~{3,})', line):
            marker = match[1][0]
            if fence == marker: fence = None
            elif fence is None: fence = marker
            if rm_fenced: continue
        if fence and rm_fenced: continue
        if match := re.match(r'^(#{1,6})\s+(.+?)\s*#*\s*$', line):
            headings.append(dict(level=len(match[1]), title=match[2], line=i))
        ms = list(_LINK_RE.finditer(line))
        for j,m in enumerate(ms):
            tail = line[m.end() : ms[j+1].start() if j+1 < len(ms) else len(line)]
            links.append(Link(len(links)+1, m[1], m[2], tail.strip().lstrip(':').strip(), i+1))

    for i,heading in enumerate(headings):
        end = next((h['line'] for h in headings[i+1:] if h['level'] <= heading['level']), len(lines))
        heading['text'] = '\n'.join(lines[heading['line']:end]).strip()

    result = HeadingDict(text)
    result.root,result._links,result.base = result,links,base
    stack,levels = [result],[0]
    for heading in headings:
        while len(stack) > 1 and levels[-1] >= heading['level']:
            stack.pop()
            levels.pop()
        parent,k = stack[-1],len(stack[-1])+1
        parent[k] = node = HeadingDict(heading['text'], heading['line']+1)
        node.root,node.title = result,heading['title']
        node.addr = f'{parent.addr}.{k}' if parent.addr else str(k)
        stack.append(node)
        levels.append(heading['level'])
    return result

# %% ../nbs/04_md_hier.ipynb #5ca82e0d
@patch
def search(self:HeadingDict,
    pat, # Case-insensitive regex, matched line by line; an invalid regex matches literally
):
    "The deepest sections owning a line matching `pat`, in document order, with match counts"
    try: r = re.compile(pat, re.IGNORECASE)
    except re.error: r = re.compile(re.escape(pat), re.IGNORECASE)
    subtree = [self, *self._walk()]
    hits = {}
    for i,line in enumerate(self.src.splitlines()):
        if not r.search(line): continue
        ln = self.start_line + i
        own = max((n for n in subtree if n.start_line <= ln <= n.end_line), key=lambda n: (n.start_line, len(n.addr)))
        node,c = hits.get(id(own), (own, 0))
        hits[id(own)] = (node, c+1)
    return Sections([n for n,_ in hits.values()], counts=[c for _,c in hits.values()])

# %% ../nbs/04_md_hier.ipynb #f79f8f5b
def create_heading_dict_file(path, rm_fenced=True):
    "Create a `HeadingDict` from the Markdown file at `path` (`~` ok), recording `path` for `refresh` and as the `base` for `follow`"
    path = Path(path).expanduser()
    res = create_heading_dict(path.read_text(), rm_fenced, base=path)
    res.path = path
    return res

# %% ../nbs/04_md_hier.ipynb #e39f3f37
class Links(L):
    "A list of `Link` rows, displayed one per line"
    def __repr__(self): return '\n'.join(map(repr, self))

@patch
def links(self:HeadingDict,
    pat='', # Case-insensitive regex matched against each link's text, target, and tail
):
    "This section's `Link` rows, numbered document-wide, filtered by `pat`"
    ls = [l for l in self.root._links if self.start_line <= l.line <= self.end_line]
    if pat:
        r = re.compile(pat, re.IGNORECASE)
        ls = [l for l in ls if r.search(l.txt) or r.search(l.url) or r.search(l.tail)]
    return Links(ls)

# %% ../nbs/04_md_hier.ipynb #e0d49d34
@patch
def follow(self:HeadingDict,
    n, # A link number, as shown by `links`
):
    "The target text of link `n`: fetched for http(s) targets, read from disk for local ones (resolved against `base`)"
    ls = self.root._links
    if not 1 <= n <= len(ls): raise IndexError(f"Link {n} is not in 1..{len(ls)}")
    url = ls[n-1].url
    base = getattr(self.root, 'base', None)
    if not re.match(r'https?://', url):
        if base is None: raise ValueError(f"{url!r} is relative and this document has no `base`; pass `base=` to `create_heading_dict`")
        if isinstance(base, Path): return (base.parent/url).read_text()
        url = urljoin(str(base), url)
    r = httpx.get(url, follow_redirects=True)
    r.raise_for_status()
    return r.text
